name: Deploy to cPanel
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # Adicione aqui quaisquer passos de build necessários
      # Por exemplo, para um projeto Node.js:
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build project
      #   run: npm run build

      - name: Deploy para cPanel via FTP (Branch Main)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./ # Diretório local para enviar (ou ./dist/ se você tiver uma build)
          server-dir: / # Pasta raiz do public_html para a versão principal
          dangerous-clean-slate: false # Não limpa o diretório de destino antes do upload
          exclude: |
            **/.git*/**
            **/.git*
            **/dev/**
            **/.github/**
            **/node_modules/**
            **/.vscode/**
            **/.DS_Store
            **/README.md

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # Adicione aqui quaisquer passos de build necessários
      # Por exemplo, para um projeto Node.js:
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build project
      #   run: npm run build

      - name: Deploy para cPanel via FTP (Branch Dev)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./ # Diretório local para enviar (ou ./dist/ se você tiver uma build)
          server-dir: /dev/ # Pasta para versão de desenvolvimento
          dangerous-clean-slate: true # Limpa o diretório de destino antes do upload
          exclude: |
            **/.git*/**
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.vscode/**
            **/.DS_Store
            **/README.md
